name: Deploy feature branches to nonproducation bucket

on:
  push:
   branches:
    - feature

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: cfst-3457-b238684f74061a455f63951c1-nonprodbucket-mxjfs9s4z36cInfo
    steps:
      - name: checkout source code
        uses: actions/checkout@v2
      - name: configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: set up Node js 
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: build Web site
        run: |
          npm ci 
          npm run build
      - name: deploy files to AWS bucket
        run: aws s3 cp public s3://${{ env.BUCKET_NAME }}/ --recursive --acl public-read


        
      




